---
title: "2022 06 27"
description: ""
date: 2022-06-27T00:28:55+09:00
image: ""
categories:
    - "日報"
tags:
    - "2022"
draft: true
---


## Commando

CIを成功させたい
- https://github.com/zztkm/commando/actions

開発用に preview 版の poetry を使っているので、pip installでpreview版をインストールしたい
- pip install --pre
    - `--pre`で preview 版もインストール対象になる
    - refs: https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-pre

以下のエラーが発生した
```
❯ pip install .
Processing /Users/ttsuruta/dev/github.com/zztkm/commando
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      Traceback (most recent call last):
        File "/Users/ttsuruta/dev/github.com/zztkm/commando/testenv/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/Users/ttsuruta/dev/github.com/zztkm/commando/testenv/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/ttsuruta/dev/github.com/zztkm/commando/testenv/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/private/var/folders/jf/ppd8_ywn5j94k064g559vgq00000gp/T/pip-build-env-w_yb6gpv/overlay/lib/python3.7/site-packages/poetry/core/masonry/api.py", line 43, in prepare_metadata_for_build_wheel
          poetry = Factory().create_poetry(Path(".").resolve(), with_dev=False)
        File "/private/var/folders/jf/ppd8_ywn5j94k064g559vgq00000gp/T/pip-build-env-w_yb6gpv/overlay/lib/python3.7/site-packages/poetry/core/factory.py", line 43, in create_poetry
          raise RuntimeError("The Poetry configuration is invalid:\n" + message)
      RuntimeError: The Poetry configuration is invalid:
        - Additional properties are not allowed ('group' was unexpected)
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
WARNING: You are using pip version 22.0.4; however, version 22.1.2 is available.
You should consider upgrading via the '/Users/ttsuruta/dev/github.com/zztkm/commando/testenv/bin/python -m pip install --upgrade pip' command.
```

対処
- 開発用の依存関係を`[tool.poetry.dev-dependencies]`に移動した
- 参考
    - https://github.com/python-poetry/poetry/issues/4983
    - https://github.com/sunscrapers/djoser/pull/663/files